# Makefile



#--- frontend -----------------------------------------------------------------
gsongs_dev:
	npm run gsongs

gsongs_production:
	PRODUCTION=1 npm run gsongs


todo_dev:
	npm run todo

todo_production:
	PRODUCTION=1 npm run todo


chords_edit_dev:
	npm run chords_edit

chords_edit_production:
	PRODUCTION=1 npm run chords_edit


chords_view_dev:
	npm run chords_view

chords_view_production:
	PRODUCTION=1 npm run chords_view
#--- frontend -----------------------------------------------------------------

